### ISSUE TITLE
Booking slot

### ISSUE THREAD

**Issue by Rossnewsome** [zaust-gh/bucktonhouseholidaycottages#37]
Hi Carl,

If you could take a look at the calendar for May. There is a booking from the 23rd which is a Saturday.

The Friday the day before doesnt show a slash through it, because the booking slots from this day are not there anymore. However, the booking from the Monday before (18th) until 22nd should still be there and is if you click on the week but the Friday doesnt make it clear as there is no slash through it, does that make sense?

**Comment by carlwoodhouse** [comment]
needs "empty/blank" changeover gradients for available and booked slots for start and end dates
